[versions]
vigilance = "220"
mixin = "0.8.5-SNAPSHOT"

[libraries]
vigilance = { module = "gg.essential:vigilance-1.8.9-forge", version.ref = "vigilance" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
