[versions]
essential = "2487"
mixin = "0.7.11-SNAPSHOT"

[libraries]
essential = { module = "gg.essential:essential-1.8.9-forge", version.ref = "essential" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
